# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static', 'static'),
    ],
    hiddenimports=[
        'pythoncom',
        'pywintypes',
        'win32com',
        'win32com.shell',
        'win32com.shell.shell',
        'win32com.shell.shellcon',
        'win32com.propsys',
        'win32com.propsys.propsys',
        'win32com.propsys.pscon',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'fastapi',
        'fastapi.responses',
        'fastapi.staticfiles',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'starlette',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'starlette.staticfiles',
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'data',
        'data.rune_pages',
        'data.item_builds',
        'data.matchup_table',
        'data.role_rates',
        'data.rules',
        'data.skill_orders',
        'data.user_config',
        'scrapers',
        'scrapers.ddragon',
        'lcu',
        'lcu.client',
        'lcu.champ_select',
        'lcu.rune_import',
        'lcu.item_import',
        'lcu.spell_import',
        'lcu.auto_detect',
        'app',
        'engine',
        'updater',
        'version',
        'config',
        'tree_executor',
        'guide_manager',
        'webview',
        'webview.platforms.edgechromium',
        'webview.platforms.winforms',
        'clr_loader',
        'pythonnet',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pytest', 'tests'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='YorickBuildAdvisor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    icon='static/icon.ico',
    version='version_info.txt',
)
